version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    

  python_server:
    build:
      context: ./python_server
      dockerfile: Dockerfile
    container_name: python_server
    
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      GTFS_URL: https://storage.googleapis.com/marduk-production/outbound/gtfs/rb_norway-aggregated-gtfs.zip
      REALTIME_URL: https://api.entur.io/realtime/v1/gtfs-rt/trip-updates
      ADDED_TRIPS: "False"
    depends_on:
      - db
    volumes:
      - ./python_server:/app

  #restarter:
    #image: docker:cli
    #volumes: 
    #- "/var/run/docker.sock:/var/run/docker.sock"
    #- "/etc/localtime:/etc/localtime:ro"  # Mount the host's local time zone configuration
    #- "/etc/timezone:/etc/timezone:ro"

    #entrypoint: ["/bin/sh","-c"]
    #command:
     # - |
       # while true; do
         # if [ "$$(date +'%H:%M')" = '10:08' ]; then
           # echo "restarting the servvice"
            #docker restart python_server
          #fi
          #sleep 60
        #done
    
    #restart: unless-stopped    
    
  spring-api:
    build:
      context: ./spring_api
      dockerfile: DockerFile
    container_name: spring_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "3001:7005"
    depends_on:
      - db
      - python_server

volumes:
  postgres_data:
